### ISSUE TITLE
Enter the command /pwik Charmander to view the spawn information and report an error

### ISSUE THREAD

**Issue by lelmc** [Flashback083/Pokewiki#1]
[22:46:28] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_292]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_292]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:325) [SpongeImplHooks.class:1.12.2-2838-7.4.2]
        at net.minecraft.server.MinecraftServer.redirect$zji000$onRun(MinecraftServer.java:4682) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at com.pixelmonmod.pixelmon.api.world.WeatherType.getLocalizedName(WeatherType.java:38) ~[WeatherType.class:8.3.3]
        at fr.pokepixel.pokewiki.info.SpawnDetails.getWeatherSpawns(SpawnDetails.java:171) ~[SpawnDetails.class:1.2.0]
        at fr.pokepixel.pokewiki.info.SpawnDetails.createPokeDetails(SpawnDetails.java:51) ~[SpawnDetails.class:1.2.0]
        at fr.pokepixel.pokewiki.gui.DisplaySpawn.lambda$getSpawnInfos$1(DisplaySpawn.java:110) ~[DisplaySpawn.class:1.2.0]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_292]
        at fr.pokepixel.pokewiki.gui.DisplaySpawn.getSpawnInfos(DisplaySpawn.java:97) ~[DisplaySpawn.class:1.2.0]
        at fr.pokepixel.pokewiki.gui.DisplaySpawn.displaySpawnGUI(DisplaySpawn.java:88) ~[DisplaySpawn.class:1.2.0]
        at fr.pokepixel.pokewiki.gui.DisplayInfo.lambda$displayInfoGUI$1(DisplayInfo.java:119) ~[DisplayInfo.class:1.2.0]
        at ca.landonjw.gooeylibs2.api.button.GooeyButton.onClick(GooeyButton.java:27) ~[GooeyButton.class:unspecified]
        at ca.landonjw.gooeylibs2.implementation.GooeyContainer.func_184996_a(GooeyContainer.java:279) ~[GooeyContainer.class:unspecified]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1162) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:219) ~[PacketPhaseUtil.class:1.12.2-2838-7.4.2]
        at net.minecraft.network.PacketThreadUtil$1.redirect$zle000$impl$redirectToPhaseTracker(SourceFile:540) ~[hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_292]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
        at com.pixelmonmod.pixelmon.api.world.WeatherType.getLocalizedName(WeatherType.java:38) ~[WeatherType.class:8.3.3]
        at fr.pokepixel.pokewiki.info.SpawnDetails.getWeatherSpawns(SpawnDetails.java:171) ~[SpawnDetails.class:1.2.0]
        at fr.pokepixel.pokewiki.info.SpawnDetails.createPokeDetails(SpawnDetails.java:51) ~[SpawnDetails.class:1.2.0]
        at fr.pokepixel.pokewiki.gui.DisplaySpawn.lambda$getSpawnInfos$1(DisplaySpawn.java:110) ~[DisplaySpawn.class:1.2.0]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_292]
        at fr.pokepixel.pokewiki.gui.DisplaySpawn.getSpawnInfos(DisplaySpawn.java:97) ~[DisplaySpawn.class:1.2.0]
        at fr.pokepixel.pokewiki.gui.DisplaySpawn.displaySpawnGUI(DisplaySpawn.java:88) ~[DisplaySpawn.class:1.2.0]
        at fr.pokepixel.pokewiki.gui.DisplayInfo.lambda$displayInfoGUI$1(DisplayInfo.java:119) ~[DisplayInfo.class:1.2.0]
        at ca.landonjw.gooeylibs2.api.button.GooeyButton.onClick(GooeyButton.java:27) ~[GooeyButton.class:unspecified]
        at ca.landonjw.gooeylibs2.implementation.GooeyContainer.func_184996_a(GooeyContainer.java:279) ~[GooeyContainer.class:unspecified]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1162) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:219) ~[PacketPhaseUtil.class:1.12.2-2838-7.4.2]
        at net.minecraft.network.PacketThreadUtil$1.redirect$zle000$impl$redirectToPhaseTracker(SourceFile:540) ~[hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_292]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
Caused by: java.lang.NullPointerException
[22:46:29] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_292]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_292]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:325) [SpongeImplHooks.class:1.12.2-2838-7.4.2]
        at net.minecraft.server.MinecraftServer.redirect$zji000$onRun(MinecraftServer.java:4682) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at com.pixelmonmod.pixelmon.api.world.WeatherType.getLocalizedName(WeatherType.java:38) ~[WeatherType.class:8.3.3]
        at fr.pokepixel.pokewiki.info.SpawnDetails.getWeatherSpawns(SpawnDetails.java:171) ~[SpawnDetails.class:1.2.0]
        at fr.pokepixel.pokewiki.info.SpawnDetails.createPokeDetails(SpawnDetails.java:51) ~[SpawnDetails.class:1.2.0]
        at fr.pokepixel.pokewiki.gui.DisplaySpawn.lambda$getSpawnInfos$1(DisplaySpawn.java:110) ~[DisplaySpawn.class:1.2.0]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_292]
        at fr.pokepixel.pokewiki.gui.DisplaySpawn.getSpawnInfos(DisplaySpawn.java:97) ~[DisplaySpawn.class:1.2.0]
        at fr.pokepixel.pokewiki.gui.DisplaySpawn.displaySpawnGUI(DisplaySpawn.java:88) ~[DisplaySpawn.class:1.2.0]
        at fr.pokepixel.pokewiki.gui.DisplayInfo.lambda$displayInfoGUI$1(DisplayInfo.java:119) ~[DisplayInfo.class:1.2.0]
        at ca.landonjw.gooeylibs2.api.button.GooeyButton.onClick(GooeyButton.java:27) ~[GooeyButton.class:unspecified]
        at ca.landonjw.gooeylibs2.implementation.GooeyContainer.func_184996_a(GooeyContainer.java:279) ~[GooeyContainer.class:unspecified]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1162) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:219) ~[PacketPhaseUtil.class:1.12.2-2838-7.4.2]
        at net.minecraft.network.PacketThreadUtil$1.redirect$zle000$impl$redirectToPhaseTracker(SourceFile:540) ~[hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_292]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]

**Comment by Flashback083** [comment]
Hi, thanks for the report, that will be fix for 1.2.0 (i'll use EN name until i found an alternative)
